# JWT Authentication Configuration
secret = "7de44c26ac7d1c57dc58f06bb1218548e43dd6700b4b1d8c8543e802a3ceff6c"

[[users]]
username = "admin"
password_hash = "$argon2id$v=19$m=19456,t=2,p=1$Q1jyewUdmakjPNt4n2LZFg$vxXidOOsjayYC+M4R0XyB8FZZ9+tLfGNZtla0nGkh4A"
role = "admin"
