apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitquan-data-testnet
  namespace: bitquan-testnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
