apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitquan-data-staging
  namespace: bitquan-staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
