apiVersion: v1
kind: Service
metadata:
  name: bitquan-node
  namespace: bitquan-staging
  labels:
    app: bitquan-node
    environment: staging
spec:
  selector:
    app: bitquan-node
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 81
    targetPort: 8081
    protocol: TCP
  - name: stratum
    port: 3333
    targetPort: 3333
    protocol: TCP
  type: ClusterIP
