#!/usr/bin/env bash
# BitQuan Phase 6.5 - Pre-Launch Preflight Validation
# Usage: ./preflight.sh --network <mainnet|testnet> --release-tag <tag>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
NETWORK=""
RELEASE_TAG=""
REPORT_FILE="${PROJECT_ROOT}/preflight_report.md"
RAW_LOG_FILE="${PROJECT_ROOT}/preflight_raw_logs.txt"

CHECKS=()
RESULTS=()
DETAILS=()
EXIT_CODE=0

usage() {
    echo "Usage: $0 --network <mainnet|testnet> --release-tag <tag>"
    echo "Example: $0 --network mainnet --release-tag v1.0.0-rc1"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --network)
            NETWORK="$2"
            shift 2
            ;;
        --release-tag)
            RELEASE_TAG="$2"
            shift 2
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "$NETWORK" ]] || [[ -z "$RELEASE_TAG" ]]; then
    usage
fi

if [[ "$NETWORK" != "mainnet" && "$NETWORK" != "testnet" ]]; then
    echo "ERROR: Network must be 'mainnet' or 'testnet'"
    exit 1
fi

echo "========================================="
echo "BitQuan Pre-Launch Preflight Validation"
echo "========================================="
echo "Network:     $NETWORK"
echo "Release Tag: $RELEASE_TAG"
echo "Started:     $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo "========================================="
echo ""

# Initialize log files
echo "BitQuan Preflight Raw Logs" > "$RAW_LOG_FILE"
echo "Network: $NETWORK | Tag: $RELEASE_TAG" >> "$RAW_LOG_FILE"
echo "Started: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$RAW_LOG_FILE"
echo "=========================================" >> "$RAW_LOG_FILE"
echo "" >> "$RAW_LOG_FILE"

run_check() {
    local check_name="$1"
    local check_script="$2"
    
    echo "Running: $check_name..."
    echo "---[ $check_name ]---" >> "$RAW_LOG_FILE"
    
    local output
    local status
    
    if output=$("$check_script" "$NETWORK" "$RELEASE_TAG" 2>&1); then
        status="PASS"
        echo "✓ $check_name: PASS"
    else
        status="FAIL"
        EXIT_CODE=1
        echo "✗ $check_name: FAIL"
    fi
    
    echo "$output" >> "$RAW_LOG_FILE"
    echo "" >> "$RAW_LOG_FILE"
    
    # Parse check output for details
    local detail=$(echo "$output" | grep -E "^CHECK \|" | tail -1 | cut -d'|' -f4- | xargs || echo "No details")
    
    CHECKS+=("$check_name")
    RESULTS+=("$status")
    DETAILS+=("$detail")
}

# Run all checks
run_check "Genesis Hash Verification" "$SCRIPT_DIR/check_genesis_hash.sh"
run_check "DNS Seeds Reachability" "$SCRIPT_DIR/check_dns_seeds.sh"
run_check "Build Reproducibility" "$SCRIPT_DIR/check_build_repro.sh"
run_check "RPC Security Guards" "$SCRIPT_DIR/check_rpc_security.sh"
run_check "Metrics Availability" "$SCRIPT_DIR/check_metrics.sh"
run_check "PoW Parameters" "$SCRIPT_DIR/check_pow_params.sh"
run_check "TLS/JWT Configuration" "$SCRIPT_DIR/check_tls_jwt.sh"

echo ""
echo "========================================="
echo "Generating Report..."
echo "========================================="

# Generate markdown report
cat > "$REPORT_FILE" <<EOF
# BitQuan Pre-Launch Preflight Report

**Network:** $NETWORK  
**Release Tag:** $RELEASE_TAG  
**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")  
**Overall Status:** $([ $EXIT_CODE -eq 0 ] && echo "✓ PASS" || echo "✗ FAIL")

---

## Summary

| Check | Status | Details |
|-------|--------|---------|
EOF

# Add check results to table
for i in "${!CHECKS[@]}"; do
    status_icon="❌"
    if [[ "${RESULTS[$i]}" == "PASS" ]]; then
        status_icon="✅"
    fi
    echo "| ${CHECKS[$i]} | $status_icon ${RESULTS[$i]} | ${DETAILS[$i]} |" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" <<EOF

---

## Pass Criteria

- ✓ Genesis hash matches documented value
- ✓ DNS seeds reachable ≥ 60%
- ✓ RPC guards active (401/408/429/431)
- ✓ Metrics endpoints expose required keys
- ✓ PoW parameters locked for mainnet
- ✓ Reproducible build hash verified
- ✓ TLS/JWT security headers present

---

## Notes

- Raw logs available at: \`preflight_raw_logs.txt\`
- For local validation: \`scripts/preflight/preflight.sh --network $NETWORK --release-tag $RELEASE_TAG\`
- For CI validation: \`gh workflow run preflight.yml -f network=$NETWORK -f release_tag=$RELEASE_TAG\`

---

*Generated by BitQuan Phase 6.5 Pre-Launch Validation System*
EOF

echo ""
echo "Report generated: $REPORT_FILE"
echo "Raw logs: $RAW_LOG_FILE"
echo ""
echo "========================================="
echo "Preflight Validation Complete"
echo "Overall Status: $([ $EXIT_CODE -eq 0 ] && echo "✓ PASS" || echo "✗ FAIL")"
echo "========================================="

exit $EXIT_CODE
