#!/bin/bash
# BitQuan Repository Safe Cleanup Script
# Generated by: Senior Code Forensic Expert
# Date: 2025-12-23
#
# FORENSIC AUDIT RESULTS:
# - agents/1,2,3: GIT WORKTREES (11GB) -> KEEP (parallel development)
# - forks/pqc_dilithium: Upstream copy (8.1MB) -> DELETE (we have pqc-dilithium-seeded)
# - docs/archive: Mixed content (13MB) -> PARTIAL DELETE
# - docs/_archive: Old BQIP specs (896KB) -> DELETE
# - *.log files: Runtime noise -> DELETE (no crash reports found)
# - *.keystore: Encrypted wallets -> MOVE to secrets/ (SECURITY)
#
# SAFETY: All deletions are MOVES to _TRASH_PENDING for manual review

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  BitQuan Safe Cleanup Script${NC}"
echo -e "${BLUE}  Forensic Audit Based - NO DATA LOSS${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Create trash directory structure: _TRASH_PENDING/YYYYMMDD_HHMMSS/
TRASH_BASE="_TRASH_PENDING"
TRASH_DIR="$TRASH_BASE/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$TRASH_DIR"
echo -e "${GREEN}✓ Created trash directory: $TRASH_DIR${NC}"
echo ""

# Create secrets directory
mkdir -p secrets
echo -e "${GREEN}✓ Created secrets/ directory${NC}"
echo ""

# ============================================================================
# SECTION 1: SECRETS - MOVE TO SECURE LOCATION
# ============================================================================
echo -e "${YELLOW}[SECTION 1] Moving Secret Files to secrets/${NC}"
echo "─────────────────────────────────────────────────────────────────"

SECRETS_MOVED=0
shopt -s nullglob
for keystore in *.keystore; do
    if [ -f "$keystore" ]; then
        mv "$keystore" "secrets/"
        echo -e "${GREEN}✓ Moved: $keystore -> secrets/${NC}"
        ((SECRETS_MOVED++))
    fi
done
shopt -u nullglob

if [ $SECRETS_MOVED -eq 0 ]; then
    echo -e "${YELLOW}⚠ No .keystore files found in root${NC}"
else
    echo -e "${GREEN}✓ Protected $SECRETS_MOVED encrypted wallet(s)${NC}"
fi
echo ""

# ============================================================================
# SECTION 2: FORKS - DELETE REDUNDANT UPSTREAM COPY
# ============================================================================
echo -e "${YELLOW}[SECTION 2] Removing Redundant Fork${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "ACTION: forks/pqc_dilithium -> $TRASH_DIR/"
echo "REASON: Upstream copy; we use crates/pqc-dilithium-seeded instead"
echo ""

if [ -d "forks/pqc_dilithium" ]; then
    mv "forks" "$TRASH_DIR/"
    echo -e "${GREEN}✓ Moved: forks/ -> $TRASH_DIR/forks/${NC}"
    echo -e "${GREEN}  (Freed ~8.1MB)${NC}"
else
    echo -e "${YELLOW}⚠ forks/pqc_dilithium not found${NC}"
fi
echo ""

# ============================================================================
# SECTION 3: DOCS ARCHIVE - CLEANUP OLD/MOVED DOCS
# ============================================================================
echo -e "${YELLOW}[SECTION 3] Cleaning docs/archive/${NC}"
echo "─────────────────────────────────────────────────────────────────"

# Create subdirectory in trash
mkdir -p "$TRASH_DIR/docs_archive"

# Files that say "Document Moved" - safe to delete
MOVED_FILES=(
    "docs/archive/DOCUMENTATION_CLEANUP_SUMMARY.md"
    "docs/archive/PRODUCTION_READINESS_AUDIT.md"
    "docs/archive/SECURITY_AUDIT_REPORT.md"
)

for file in "${MOVED_FILES[@]}"; do
    if [ -f "$file" ]; then
        mv "$file" "$TRASH_DIR/docs_archive/"
        echo -e "${GREEN}✓ Moved: $file${NC}"
        echo -e "${YELLOW}  (Document was moved to new location)${NC}"
    fi
done

# Old reports that can be archived
OLD_REPORTS=(
    "docs/archive/beta-tester-recruitment.md"
    "docs/archive/integration-success-report.md"
    "docs/archive/CI_ASSESSMENT.md"
    "docs/archive/CRITICAL_FIXES_COMPLETION_SUMMARY.md"
    "docs/archive/integration-success-report.md"
    "docs/archive/command.txt"
    "docs/archive/COMMIT_MESSAGE.txt"
)

for file in "${OLD_REPORTS[@]}"; do
    if [ -f "$file" ]; then
        mv "$file" "$TRASH_DIR/docs_archive/"
        echo -e "${GREEN}✓ Moved: $file${NC}"
        echo -e "${YELLOW}  (Old report/document)${NC}"
    fi
done

echo -e "${YELLOW}⚠ KEPT: docs/archive/AUDIT_HANDOFF.md (Critical security document)${NC}"
echo ""

# ============================================================================
# SECTION 4: DOCS _ARCHIVE - OLD BQIP SPECS
# ============================================================================
echo -e "${YELLOW}[SECTION 4] Removing docs/_archive/${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "ACTION: docs/_archive/ -> $TRASH_DIR/docs__archive/"
echo "REASON: Old BQIP drafts (BQIP-0001 through BQIP-0004)"
echo ""

if [ -d "docs/_archive" ]; then
    mv "docs/_archive" "$TRASH_DIR/docs__archive"
    echo -e "${GREEN}✓ Moved: docs/_archive/ -> $TRASH_DIR/docs__archive/${NC}"
    echo -e "${GREEN}  (Freed ~896KB)${NC}"
else
    echo -e "${YELLOW}⚠ docs/_archive not found${NC}"
fi
echo ""

# ============================================================================
# SECTION 5: LOG FILES - RUNTIME NOISE
# ============================================================================
echo -e "${YELLOW}[SECTION 5] Removing Log Files${NC}"
echo "─────────────────────────────────────────────────────────────────"

# Create subdirectory in trash for logs
mkdir -p "$TRASH_DIR/logs"

LOGS_DELETED=0
shopt -s nullglob
for logfile in *.log; do
    if [ -f "$logfile" ]; then
        mv "$logfile" "$TRASH_DIR/logs/"
        echo -e "${GREEN}✓ Moved: $logfile${NC}"
        ((LOGS_DELETED++))
    fi
done
shopt -u nullglob

if [ -f "mining_output.txt" ]; then
    mv "mining_output.txt" "$TRASH_DIR/logs/"
    echo -e "${GREEN}✓ Moved: mining_output.txt${NC}"
    ((LOGS_DELETED++))
fi

if [ $LOGS_DELETED -eq 0 ]; then
    echo -e "${YELLOW}⚠ No log files found${NC}"
else
    echo -e "${GREEN}✓ Removed $LOGS_DELETED log file(s)${NC}"
fi
echo ""

# ============================================================================
# SECTION 6: AGENTS - KEEP (GIT WORKTREES)
# ============================================================================
echo -e "${YELLOW}[SECTION 6] agents/ Directory${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo -e "${GREEN}✓ KEPT: agents/ (11GB)${NC}"
echo -e "${YELLOW}  These are GIT WORKTREES for parallel development${NC}"
echo -e "${YELLOW}  agents/1, agents/2, agents/3 are NOT duplicates!${NC}"
echo ""

# ============================================================================
# FINAL REPORT
# ============================================================================
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  CLEANUP SUMMARY${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Calculate space freed
TRASH_SIZE=$(du -sh "$TRASH_DIR" 2>/dev/null | cut -f1)
echo -e "${GREEN}Total moved to trash: $TRASH_SIZE${NC}"
echo ""
echo -e "${YELLOW}📦 Trash location: $TRASH_DIR/${NC}"
echo ""
echo -e "${GREEN}✓ Secrets protected: $SECRETS_MOVED wallet(s)${NC}"
echo -e "${GREEN}✓ Logs cleaned: $LOGS_DELETED files${NC}"
echo -e "${GREEN}✓ Docs archived: Old/moved documents${NC}"
echo -e "${GREEN}✓ Forks cleaned: Redundant upstream copy${NC}"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANT SECURITY NOTES:${NC}"
echo -e "${YELLOW}   1. Review $TRASH_DIR/ before permanent deletion${NC}"
echo -e "${YELLOW}   2. secrets/ folder contains encrypted wallets${NC}"
echo -e "${YELLOW}   3. Consider adding 'secrets/' to .gitignore if not already${NC}"
echo -e "${YELLOW}   4. agents/ worktrees (11GB) are intentional - do NOT delete${NC}"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  To permanently delete trash: rm -rf $TRASH_DIR${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
