#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Deterministic random number generation backed by ChaCha20.

use crate::rng::hkdf_expand;
#[cfg(not(feature = "deterministic_tests"))]
use rand::rngs::OsRng;
use rand_chacha::ChaCha20Rng;
use rand_core::{RngCore, SeedableRng};
use thiserror::Error;
use zeroize::Zeroize;

#[cfg(feature = "deterministic_tests")]
use hex::decode as hex_decode;

/// Errors produced by the BitQuan RNG service.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum RngError {
    /// The operating system CSPRNG did not supply entropy.
    #[error("OS entropy unavailable")]
    OsEntropyUnavailable,
    /// A deterministic seed was malformed or the wrong length.
    #[error("invalid deterministic seed")]
    InvalidSeed,
}

/// Trait describing high-level random byte generation utilities.
pub trait RandomSource {
    /// Fills `out` with random bytes.
    fn fill(&mut self, out: &mut [u8]) -> Result<(), RngError>;

    /// Returns exactly `n` random bytes.
    fn bytes(&mut self, n: usize) -> Result<Vec<u8>, RngError> {
        let mut buf = vec![0u8; n];
        self.fill(&mut buf)?;
        Ok(buf)
    }

    /// Returns a uniformly random `u64` value.
    fn u64(&mut self) -> Result<u64, RngError> {
        let mut buf = [0u8; 8];
        self.fill(&mut buf)?;
        Ok(u64::from_le_bytes(buf))
    }
}

/// Long-lived deterministic random byte generator with HKDF substreams.
pub struct RngService {
    drbg: ChaCha20Rng,
    master_seed: [u8; 32],
}

impl Drop for RngService {
    fn drop(&mut self) {
        self.master_seed.zeroize();
    }
}

impl RngService {
    /// Creates a new RNG service seeded from the OS CSPRNG or deterministic seed.
    pub fn new() -> Result<Self, RngError> {
        #[cfg(feature = "deterministic_tests")]
        {
            let seed = deterministic_seed()?;
            let drbg = ChaCha20Rng::from_seed(seed);
            return Ok(Self {
                drbg,
                master_seed: seed,
            });
        }

        #[cfg(not(feature = "deterministic_tests"))]
        {
            let mut master_seed = [0u8; 32];
            OsRng
                .try_fill_bytes(&mut master_seed)
                .map_err(|_| RngError::OsEntropyUnavailable)?;
            let drbg = ChaCha20Rng::from_seed(master_seed);
            Ok(Self { drbg, master_seed })
        }
    }

    /// Derives a new RNG stream using HKDF-SHA256 domain separation.
    pub fn derive_stream(&self, label: &str) -> Self {
        let derived_seed = hkdf_expand(&self.master_seed, label);
        let drbg = ChaCha20Rng::from_seed(derived_seed);
        Self {
            drbg,
            master_seed: derived_seed,
        }
    }
}

impl RandomSource for RngService {
    fn fill(&mut self, out: &mut [u8]) -> Result<(), RngError> {
        self.drbg.fill_bytes(out);
        Ok(())
    }
}

#[cfg(feature = "deterministic_tests")]
fn deterministic_seed() -> Result<[u8; 32], RngError> {
    let seed_hex = std::env::var("BQ_TEST_SEED").unwrap_or_else(|_| "01".repeat(32));
    let bytes = hex_decode(seed_hex).map_err(|_| RngError::InvalidSeed)?;
    if bytes.len() != 32 {
        return Err(RngError::InvalidSeed);
    }
    let mut seed = [0u8; 32];
    seed.copy_from_slice(&bytes);
    Ok(seed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;
    use std::collections::HashSet;

    #[test]
    fn not_all_zero() {
        let mut rng = RngService::new().expect("entropy available");
        let bytes = rng.bytes(32).expect("generated bytes");
        assert!(bytes.iter().any(|&b| b != 0));
    }

    #[test]
    fn substream_differs() {
        let rng = RngService::new().expect("entropy available");
        let mut stream_a = rng.derive_stream("wallet-seed");
        let mut stream_b = rng.derive_stream("tx-sig");
        let a = stream_a.bytes(32).expect("a bytes");
        let b = stream_b.bytes(32).expect("b bytes");
        assert_ne!(a, b);
    }

    proptest! {
        #[test]
        fn unique_16b(count in 1000usize..1500usize) {
            let mut rng = RngService::new().expect("entropy available");
            let mut seen: HashSet<Vec<u8>> = HashSet::with_capacity(count);
            for _ in 0..count {
                let value = rng.bytes(16).expect("sample");
                assert!(seen.insert(value));
            }
        }
    }

    #[cfg(feature = "deterministic_tests")]
    #[test]
    fn deterministic_seed_from_env_or_default() {
        let original = std::env::var("BQ_TEST_SEED").ok();
        std::env::remove_var("BQ_TEST_SEED");
        let first = RngService::new().expect("seeded");
        std::env::set_var(
            "BQ_TEST_SEED",
            "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
        );
        let second = RngService::new().expect("seeded");
        assert_ne!(first.master_seed, second.master_seed);
        match original {
            Some(value) => std::env::set_var("BQ_TEST_SEED", value),
            None => std::env::remove_var("BQ_TEST_SEED"),
        }
    }
}
